language: python

sudo: false

python:
  - "3.6"

sudo: false

# Miniconda copied from
# https://gist.github.com/dan-blanchard/7045057
before_install:
  - MINICONDA=Miniconda3-latest-Linux-x86_64.sh
  - wget http://repo.continuum.io/miniconda/${MINICONDA} -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda create --yes -n test_env python=$TRAVIS_PYTHON_VERSION pytables
  - source activate test_env
  - pip install webtest flake8 coverage coveralls codecov sphinx

script:
  - flake8 writer wsgi
  - coverage run -m unittest discover tests -v
  - sphinx-build -anW doc doc/_build/html

after_success:
  - coveralls
