language: python
python:
  - "3.6"

sudo: false

# Miniconda copied from
# https://gist.github.com/dan-blanchard/7045057
before_install:
  - MINICONDA=Miniconda3-latest-Linux-x86_64.sh
  - wget http://repo.continuum.io/miniconda/${MINICONDA} -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda

install:
  - conda create --yes -n test_env python=$TRAVIS_PYTHON_VERSION pytables
  - source activate test_env
  - make devinstall

script:
  - make test

after_success:
  - coveralls
  - codecov

before_deploy:
  - touch doc/_build/html/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: doc/_build/html
  email: beheer@hisparc.nl
  name: HiSPARC-Bot
  on:
    branch: master
    python: 3.6
