[tool.ruff]
line-length = 120
target-version = 'py310'

[tool.ruff.format]
quote-style = 'single'

[tool.ruff.lint]
select = ['ALL']  # https://docs.astral.sh/ruff/rules/
ignore = [
    'ANN',  # Type annotations not enforced
    'D',  # Ignore docstring checks
    'G004',  # Allow f-string in logging
    'PTH',  # Still using os.path
    'PT',  # Not using pytest
    'RET',  # Allow elif/else after return
]

[tool.ruff.lint.per-file-ignores]
'migration/*.py' = ['T201']  # Allow printing
'scripts/*.py' = ['T201']  # Allow printing

[tool.ruff.lint.flake8-quotes]
inline-quotes = 'single'

[tool.ruff.lint.isort]
lines-between-types = 1
section-order = [
    'future',
    'standard-library',
    'third-party',
    'first-party',
    'local-folder',
]

[tool.coverage.run]
branch = true
source = [
    'tests',
    'writer',
    'wsgi',
]
