name: Run tests

on:
  push:

defaults:
  run:
    shell: bash -l {0}

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [
            '3.8',
            '3.9',
            '3.10',
        ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
      - run: make devinstall
      - run: make unittests

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install ruff
      - run: make linttest

  docs:
    if: github.ref == 'refs/heads/master'
    needs: [tests, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: '3.10'
          auto-update-conda: true
      - run: make devinstall
      - run: make doctest
      - uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/_build/html
          publish_branch: gh-pages
          force_orphan: true
